export const SITE_NAME = 'Agroprice'
export const API_URL = 'http://127.0.0.1:8000/api'
// export const API_URL = 'https://manager.agroprice.kz/api'
export const STORAGE_URL = 'http://127.0.0.1:8000/storage'
// export const STORAGE_URL = 'https://manager.agroprice.kz/storage'
export const SITE_KEY = '6Lf0hWIkAAAAAADV6WvtBvtrEcBxKaPq1rI9cAKJ'
// export const SITE_KEY = '6LfgHIkkAAAAAGx4kAAM6TXT-ru029wHtGG2kBaX'